### ISSUE TITLE
LMAO

### ISSUE THREAD

**Issue by Radioplus** [kylerittenhause/mirai-client-decompiled#2]
YOU THINK I DIDNT LOOK AT THE CODE AND DIDNT SEE KAMI AND XULU CODE XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD MONKEY DUMBASSES

**Comment by kylerittenhause** [comment]
What in the heck are you talking about, You think i coded this client?

**Comment by Radioplus** [comment]
> What in the heck are you talking about, You think i coded this client?

keep coping dumbass, first, where in tf is the settings.gradle file? you cant even build this shit, second, we saw the code on the modules, nice try thinking we wouldn't look into it just to see kami code, this source code is literally rendered useless also WHERE IN TF IS THE CLIENT.JAVA FILE, LMAO THIS SOURCE IS LITERALLY THE MOST USELESS SHIT IVE EVER SEEN, LMAO NIGGA LOOKIN FOR ATTENTION GOES AND SAYS THAT HE DECOMPILED IT XD, I BET YOU DONT EVEN KNOW WHAT DECOMPILE MEANS XDXD COPE KID

**Comment by Radioplus** [comment]
> What in the heck are you talking about, You think i coded this client?

also the license file

**Comment by Radioplus** [comment]
> What in the heck are you talking about, You think i coded this client?

this is the funniest try of a leaked client I've ever seen.

**Comment by Radioplus** [comment]
> What in the heck are you talking about, You think i coded this client?

btw dont try to get attention when you fucked up so badly, thinking saying my name will scare me OH SHIVER ME TIMBERS HE SAID MY NAME, lmao we are continuing mirai just to piss your ass off 🤓

**Comment by kylerittenhause** [comment]
> > What in the heck are you talking about, You think i coded this client?
> 
> keep coping dumbass, first, where in tf is the settings.gradle file? you cant even build this shit, second, we saw the code on the modules, nice try thinking we wouldn't look into it just to see kami code, this source code is literally rendered useless also WHERE IN TF IS THE CLIENT.JAVA FILE, LMAO THIS SOURCE IS LITERALLY THE MOST USELESS SHIT IVE EVER SEEN, LMAO NIGGA LOOKIN FOR ATTENTION GOES AND SAYS THAT HE DECOMPILED IT XD, I BET YOU DONT EVEN KNOW WHAT DECOMPILE MEANS XDXD COPE KID

Holy fuck bro keep raging, You obviously haven't decompiled a client like forever, Tell me what's gradle is for, it is for building that's it, Don't believe me? We know you are retarded so how about you try it yourself, make a gradle project and build a jar and decompile it and tell me what you see, Do you think there will be everything from the project? seriously bro you are retarded, Do you remember when you wanted to join brownmen and named your youtube change "AlphaRadio - Brownmen", That was pretty cringe like wth do you think you are, Everyone at brownmen were laughing at you, If you don't agree that you are retarded then you can never learn bro, Anyway basically java decompilers dont need to compile MANIFEST.MF into gradle files and they cant be accurate and that can be done manually and you are retarded

**Comment by BruzzTheHuzz0** [comment]
i love how he doesnt respond because he know he was defeated

**Comment by Radioplus** [comment]
i love how you keep responding to a troll, mrongrol in azrns dms being a fanboy, keep larping.

**Comment by Radioplus** [comment]
so yes, your a nigger sans

**Comment by kylerittenhause** [comment]
> i love how you keep responding to a troll, mrongrol in azrns dms being a fanboy, keep larping.

ah yes, ez nn larp, please find more reddit one liners

**Comment by Radioplus** [comment]
nigga cum

**Comment by kylerittenhause** [comment]
so funny
